# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b555b627e8b93b9ef04e62ccefa8fac0cd84b32641150e50bee79402e110dc38ee42709d66e1f5dd723e3dd38e1997849ee170c56810be670bf9c5daee0d7c12

test:
  secret_key_base: ad01bea93601edd572f302da2aefda94588647f1ecffec35bc1f34687389c6bd2f2ef8c6a08169c2f696718a70ec33d82deb6141150a4ad1e98b0ef0c975b6fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
